package com.tez.hrMvc.model;
// Generated 2 juin 2018 14:26:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ImagesTbl generated by hbm2java
 */
@Entity
@Table(name = "IMAGES_TBL")
public class ImagesTbl implements java.io.Serializable {

	private BigDecimal imageId;
	private Blob imageBlob;
	private String imagesName;
	private long objectVersionNumber;
	private Set<UsrMen> usrMens = new HashSet<UsrMen>(0);

	public ImagesTbl() {
	}

	public ImagesTbl(BigDecimal imageId, String imagesName, long objectVersionNumber) {
		this.imageId = imageId;
		this.imagesName = imagesName;
		this.objectVersionNumber = objectVersionNumber;
	}

	public ImagesTbl(BigDecimal imageId, Blob imageBlob, String imagesName, long objectVersionNumber,
			Set<UsrMen> usrMens) {
		this.imageId = imageId;
		this.imageBlob = imageBlob;
		this.imagesName = imagesName;
		this.objectVersionNumber = objectVersionNumber;
		this.usrMens = usrMens;
	}

	@Id

	@Column(name = "IMAGE_ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getImageId() {
		return this.imageId;
	}

	public void setImageId(BigDecimal imageId) {
		this.imageId = imageId;
	}

	@Column(name = "IMAGE_BLOB")
	public Blob getImageBlob() {
		return this.imageBlob;
	}

	public void setImageBlob(Blob imageBlob) {
		this.imageBlob = imageBlob;
	}

	@Column(name = "IMAGES_NAME", nullable = false, length = 1020)
	public String getImagesName() {
		return this.imagesName;
	}

	public void setImagesName(String imagesName) {
		this.imagesName = imagesName;
	}

	@Column(name = "OBJECT_VERSION_NUMBER", nullable = false, precision = 10, scale = 0)
	public long getObjectVersionNumber() {
		return this.objectVersionNumber;
	}

	public void setObjectVersionNumber(long objectVersionNumber) {
		this.objectVersionNumber = objectVersionNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "imagesTbl")
	public Set<UsrMen> getUsrMens() {
		return this.usrMens;
	}

	public void setUsrMens(Set<UsrMen> usrMens) {
		this.usrMens = usrMens;
	}

}
