package com.tez.hrMvc.model;
// Generated 2 juin 2018 14:26:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Nbrevisit generated by hbm2java
 */
@Entity
@Table(name = "NBREVISIT")
public class Nbrevisit implements java.io.Serializable {

	private BigDecimal idVisit;
	private Date dateVisit;
	private String util;

	public Nbrevisit() {
	}

	public Nbrevisit(BigDecimal idVisit) {
		this.idVisit = idVisit;
	}

	public Nbrevisit(BigDecimal idVisit, Date dateVisit, String util) {
		this.idVisit = idVisit;
		this.dateVisit = dateVisit;
		this.util = util;
	}

	@Id

	@Column(name = "ID_VISIT", unique = true, nullable = false, scale = 0)
	public BigDecimal getIdVisit() {
		return this.idVisit;
	}

	public void setIdVisit(BigDecimal idVisit) {
		this.idVisit = idVisit;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_VISIT", length = 7)
	public Date getDateVisit() {
		return this.dateVisit;
	}

	public void setDateVisit(Date dateVisit) {
		this.dateVisit = dateVisit;
	}

	@Column(name = "UTIL", length = 40)
	public String getUtil() {
		return this.util;
	}

	public void setUtil(String util) {
		this.util = util;
	}

}
