package com.tez.hrMvc.model;
// Generated 2 juin 2018 14:26:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Regions generated by hbm2java
 */
@Entity
@Table(name = "REGIONS")
public class Regions implements java.io.Serializable {

	private Integer regionId;
	private String regionName;
	private Set<Countries> countrieses = new HashSet<Countries>(0);

	public Regions() {
	}


	@Transient
	public boolean isNew() {
		return (this.getRegionId() == null);
	}

	public Regions(Integer regionId) {
		this.regionId = regionId;
	}

	public Regions(Integer regionId, String regionName, Set<Countries> countrieses) {
		this.regionId = regionId;
		this.regionName = regionName;
		this.countrieses = countrieses;
	}

	@Id

	@Column(name = "REGION_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getRegionId() {
		return this.regionId;
	}

	public void setRegionId(Integer regionId) {
		this.regionId = regionId;
	}

	@Column(name = "REGION_NAME", length = 25)
	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regions")
	public Set<Countries> getCountrieses() {
		return this.countrieses;
	}

	public void setCountrieses(Set<Countries> countrieses) {
		this.countrieses = countrieses;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((regionId == null) ? 0 : regionId.hashCode());
		result = prime * result + ((regionName == null) ? 0 : regionName.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Regions other = (Regions) obj;
		if (regionId == null) {
			if (other.regionId != null) {
				return false;
			}
		} else if (!regionId.equals(other.regionId)) {
			return false;
		}
		if (regionName == null) {
			if (other.regionName != null) {
				return false;
			}
		} else if (!regionName.equals(other.regionName)) {
			return false;
		}
		return true;
	}

}
