package com.tez.hrMvc.model;
// Generated 2 juin 2018 14:26:26 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsrMen generated by hbm2java
 */
@Entity
@Table(name = "USR_MEN")
public class UsrMen implements java.io.Serializable {

	private String util;
	private ImagesTbl imagesTbl;
	private Date dateCrt;
	private Date dateDeb;
	private Date dateFin;
	private long idtMatag;
	private String mail;
	private String nom;
	private String prenom;
	private String pwd;
	private String utilValid;
	private Set<UsrProfilUtil> usrProfilUtils = new HashSet<UsrProfilUtil>(0);
	private Set<UsrMenTree> usrMenTrees = new HashSet<UsrMenTree>(0);

	public UsrMen() {
	}

	public UsrMen(String util, long idtMatag) {
		this.util = util;
		this.idtMatag = idtMatag;
	}

	public UsrMen(String util, ImagesTbl imagesTbl, Date dateCrt, Date dateDeb, Date dateFin, long idtMatag,
			String mail, String nom, String prenom, String pwd, String utilValid, Set<UsrProfilUtil> usrProfilUtils,
			Set<UsrMenTree> usrMenTrees) {
		this.util = util;
		this.imagesTbl = imagesTbl;
		this.dateCrt = dateCrt;
		this.dateDeb = dateDeb;
		this.dateFin = dateFin;
		this.idtMatag = idtMatag;
		this.mail = mail;
		this.nom = nom;
		this.prenom = prenom;
		this.pwd = pwd;
		this.utilValid = utilValid;
		this.usrProfilUtils = usrProfilUtils;
		this.usrMenTrees = usrMenTrees;
	}

	@Id

	@Column(name = "UTIL", unique = true, nullable = false, length = 800)
	public String getUtil() {
		return this.util;
	}

	public void setUtil(String util) {
		this.util = util;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IMAGE_ID")
	public ImagesTbl getImagesTbl() {
		return this.imagesTbl;
	}

	public void setImagesTbl(ImagesTbl imagesTbl) {
		this.imagesTbl = imagesTbl;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_CRT", length = 7)
	public Date getDateCrt() {
		return this.dateCrt;
	}

	public void setDateCrt(Date dateCrt) {
		this.dateCrt = dateCrt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DEB", length = 7)
	public Date getDateDeb() {
		return this.dateDeb;
	}

	public void setDateDeb(Date dateDeb) {
		this.dateDeb = dateDeb;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_FIN", length = 7)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@Column(name = "IDT_MATAG", nullable = false, precision = 10, scale = 0)
	public long getIdtMatag() {
		return this.idtMatag;
	}

	public void setIdtMatag(long idtMatag) {
		this.idtMatag = idtMatag;
	}

	@Column(name = "MAIL", length = 2000)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "NOM", length = 400)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", length = 400)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "PWD", length = 4000)
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	@Column(name = "UTIL_VALID", length = 160)
	public String getUtilValid() {
		return this.utilValid;
	}

	public void setUtilValid(String utilValid) {
		this.utilValid = utilValid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usrMen")
	public Set<UsrProfilUtil> getUsrProfilUtils() {
		return this.usrProfilUtils;
	}

	public void setUsrProfilUtils(Set<UsrProfilUtil> usrProfilUtils) {
		this.usrProfilUtils = usrProfilUtils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usrMen")
	public Set<UsrMenTree> getUsrMenTrees() {
		return this.usrMenTrees;
	}

	public void setUsrMenTrees(Set<UsrMenTree> usrMenTrees) {
		this.usrMenTrees = usrMenTrees;
	}

}
