package com.tez.hrMvc.model;
// Generated 2 juin 2018 14:26:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsrMenTreeId generated by hbm2java
 */
@Embeddable
public class UsrMenTreeId implements java.io.Serializable {

	private BigDecimal menuId;
	private String util;

	public UsrMenTreeId() {
	}

	public UsrMenTreeId(BigDecimal menuId, String util) {
		this.menuId = menuId;
		this.util = util;
	}

	@Column(name = "MENU_ID", nullable = false, scale = 0)
	public BigDecimal getMenuId() {
		return this.menuId;
	}

	public void setMenuId(BigDecimal menuId) {
		this.menuId = menuId;
	}

	@Column(name = "UTIL", nullable = false, length = 120)
	public String getUtil() {
		return this.util;
	}

	public void setUtil(String util) {
		this.util = util;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsrMenTreeId))
			return false;
		UsrMenTreeId castOther = (UsrMenTreeId) other;

		return ((this.getMenuId() == castOther.getMenuId()) || (this.getMenuId() != null
				&& castOther.getMenuId() != null && this.getMenuId().equals(castOther.getMenuId())))
				&& ((this.getUtil() == castOther.getUtil()) || (this.getUtil() != null && castOther.getUtil() != null
						&& this.getUtil().equals(castOther.getUtil())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMenuId() == null ? 0 : this.getMenuId().hashCode());
		result = 37 * result + (getUtil() == null ? 0 : this.getUtil().hashCode());
		return result;
	}

}
