package com.tez.hrMvc.model;
// Generated 2 juin 2018 14:26:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsrProfilUtil generated by hbm2java
 */
@Entity
@Table(name = "USR_PROFIL_UTIL")
public class UsrProfilUtil implements java.io.Serializable {

	private UsrProfilUtilId id;
	private Profil profil;
	private UsrMen usrMen;
	private String pageTrac;
	private String utilTrac;

	public UsrProfilUtil() {
	}

	public UsrProfilUtil(UsrProfilUtilId id, Profil profil, UsrMen usrMen) {
		this.id = id;
		this.profil = profil;
		this.usrMen = usrMen;
	}

	public UsrProfilUtil(UsrProfilUtilId id, Profil profil, UsrMen usrMen, String pageTrac, String utilTrac) {
		this.id = id;
		this.profil = profil;
		this.usrMen = usrMen;
		this.pageTrac = pageTrac;
		this.utilTrac = utilTrac;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codeProfil", column = @Column(name = "CODE_PROFIL", nullable = false, scale = 0)),
			@AttributeOverride(name = "util", column = @Column(name = "UTIL", nullable = false, length = 120)) })
	public UsrProfilUtilId getId() {
		return this.id;
	}

	public void setId(UsrProfilUtilId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_PROFIL", nullable = false, insertable = false, updatable = false)
	public Profil getProfil() {
		return this.profil;
	}

	public void setProfil(Profil profil) {
		this.profil = profil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UTIL", nullable = false, insertable = false, updatable = false)
	public UsrMen getUsrMen() {
		return this.usrMen;
	}

	public void setUsrMen(UsrMen usrMen) {
		this.usrMen = usrMen;
	}

	@Column(name = "PAGE_TRAC", length = 1000)
	public String getPageTrac() {
		return this.pageTrac;
	}

	public void setPageTrac(String pageTrac) {
		this.pageTrac = pageTrac;
	}

	@Column(name = "UTIL_TRAC", length = 120)
	public String getUtilTrac() {
		return this.utilTrac;
	}

	public void setUtilTrac(String utilTrac) {
		this.utilTrac = utilTrac;
	}

}
